### ISSUE TITLE
Pulse Rifle Alt Fire

### ISSUE THREAD

**Issue by Viz-Titan** [DS-13-Dev-Team/DS13-2.0#109]
![image](https://github.com/DS-13-Dev-Team/DS13-2.0/assets/104938566/23bc7788-5380-4899-9927-d73ff1911e0e)

The pulse rifle alt fire shots remaining can be different compared to _actual_ shots remaining. 
When full, it works fine. 50 shots in the mag, gives 2 grenades to fire off since each costs 25 normal shots. Simple.
But when it goes to 49 shots, the game displays that it only has 1 grenade (As if it needs all 25 shots to spend to make the grenade shot). Then in use, it still fires 2 grenades, since it doesn't necessarily need ALL 25 shots, it just needs _a_ shot. 
So you can use 24 shots of normal pulse, then swap to the alt and **still** have 2 grenades to use. 
Even worse, due to this, you can empty a mag, put one round back in, and use it in the rifle to fire a grenade. Then just repeat with each of the 50 rounds, resulting in a potential of 50 grenades from the one mag. 
Don't think it is a rounding issue, unless it is acting poorly somehow. Might be due to adding a round for the chamber or so? Despite being open bolt, dunno.

Another issue is that, when swapping firemodes for the alt fire, the ammo isn't conserved. It is simply converting the mag. So swapping between firemodes can likely result in a loss of ammo. For example, 34 rounds turns into the theoretical (but not actual, as stated before) 1 grenade. Converting this back, it only gives 25.
The only potential, theoretical fix for this that I can think of (though unlikely to work)... Is to try to keep track of the ammo usage, even keeping with decimals if need be. So 34 rounds / 25 is 1.36 (Can round it just to nearest 0.01 if needed). Grenade fires, then it subtracts 1 of course. It shouldn't be able to fire again, but still has the remaining 0.36 left. Once the firemode is switched, it turns it back into normal ammo. 0.36 x 25 = 9 rounds left.

Swapping in standard mags into the gun while the alt firemode is still selected can cause varying issues and bugs. 
A potential fix may be that it sees a mag is inserted that isn't of the converted alt ammo type, and it does the conversion to alt ammo.
Check for the other way around too of course.

If you wish to communicate with me, I encourage you to mention me on the DS13 Discord! Name is simply "Viz". I'm not very technically minded in actuality with creating new code, but will still hopefully be able to be of aid elsewise.

**Comment by Viz-Titan** [comment]
@CometBlaze 
I can bugtest it on the weekend, when we are doing a test. Will be able to get some more info and screenshots if you want. 
Feel free to ask questions in #dev-closet of course, or DM me

**Comment by MisterGrimm** [comment]
Fixed in PR #207
