### ISSUE TITLE
Necromorphs cant go up ladders

### ISSUE THREAD

**Issue by chesse20** [DS-13-Dev-Team/DS13-2.0#139]
## Testmerges:
[#128: 'Aegis7' by blackwolf602 at commit 6496daf920](https://github.com/DS-13-Dev-Team/DS13-2.0/pull/128)
[#131: 'Redbot' by RegJoe at commit ba2c73fd0d](https://github.com/DS-13-Dev-Team/DS13-2.0/pull/131)

## Reproduction:

Be Necromorph
Use ladder
Attack ladder instead of going up or down

**Comment by MisterGrimm** [comment]
Solved in #182
