### ISSUE TITLE
Cyborg stuck in crit wouldnt die

### ISSUE THREAD

**Issue by ISOSS13** [DS-13-Dev-Team/DS13-2.0#190]
As a security cyborg I was fighting 3 necros (e-slasher, hunter, brute), they must have hit me over 70 times before I died and I was already at 2 modules disabled. I think what killed me in the end may have been the brutes special attack?

The majority of the hits came from the hunter. Perhaps hunters cant kill cyborgs for some reason? I havent experienced this with slashers in other rounds which makes me think maybe its a problem on the hunters end?

Forgot round ID, sorry.

Easy solution would be to disable cyborgs but I hope they're kept.

**Comment by MisterGrimm** [comment]
Cyborg is not intended to stay, it will be removed after more pressing matters are dealt with.
