### ISSUE TITLE
SUGGESTION: add random name & random body to character setup

### ISSUE THREAD

**Issue by Cartlord** [DS-13-Dev-Team/DS13-2.0#219]
## Feature description
Make it so that you can, from the Character Setup menu, randomize your character's name or body - as well as adding an option to auto-randomize it every round.

## Why is this feature needed/good for the game?
It makes it feasible to not be a static, which has benefits like not being subject to metagrudges or metafriending.

**Comment by MisterGrimm** [comment]
> ## Feature description
> 
> Make it so that you can, from the Character Setup menu, randomize your character's name or body - as well as adding an option to auto-randomize it every round.
> ## Why is this feature needed/good for the game?
> 
> It makes it feasible to not be a static, which has benefits like not being subject to metagrudges or metafriending.

This is a upstream suggestion, please send this suggestion to Daedalus Dock. https://github.com/DaedalusDock/daedalusdock
